apiVersion: v1
entries:
  hadoop:
  - apiVersion: v1
    appVersion: 3.3.2
    created: "2024-01-22T16:06:06.302252+08:00"
    description: The Apache Hadoop software library is a framework that allows for
      the distributed processing of large data sets across clusters of computers using
      simple programming models.
    digest: 1b526a24988e3a02ec2f740d5ee1371458a1f811d16d5be1261d3bc74cbc53a8
    home: https://hadoop.apache.org/
    icon: http://hadoop.apache.org/images/hadoop-logo.jpg
    maintainers:
    - email: github@farberg.de
      name: pfisterer
      url: http://github.com/pfisterer
    name: hadoop
    sources:
    - https://github.com/pfisterer/apache-hadoop-helm
    - https://github.com/apache/hadoop
    urls:
    - https://katool.github.io/charts/hadoop-1.0.0.tgz
    version: 1.0.0
  hue:
  - apiVersion: v2
    appVersion: 4.10.0
    created: "2024-01-22T16:06:06.307108+08:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: ~11.6.0
    description: Hue is an SQL Cloud Editor for Data Warehouses and Databases.
    digest: be919bdf59a6a1c518377cd5fd58949934b1c15ff96107714a944ebb933db931
    home: http://gethue.com/
    icon: https://raw.githubusercontent.com/cloudera/hue/master/docs/images/hue_logo.png
    keywords:
    - Hue
    - SQL
    - Editor
    - Catalog
    - Visualization
    maintainers:
    - email: charts@katool.tech
      name: katool
    name: hue
    sources:
    - https://github.com/cloudera/hue
    - https://hub.docker.com/u/gethue
    urls:
    - https://katool.github.io/charts/hue-1.0.5.tgz
    version: 1.0.5
generated: "2024-01-22T16:06:06.29992+08:00"
